- .pre-commit-config.yaml
- book.toml
> chore: remove linkchecker exceptions

- .editorconfig
- .github/actions/build-mdbook/action.yaml
- README.md
- book.toml
- docs/README.md
- docs/design/operations-off-chain.md
- docs/design/properties.md
- docs/dev-guide/dev-guide.md
- docs/dev-guide/dev-operations.md
- docs/dev-guide/sui-struct.md
- docs/usage/setup.md
- docs/usage/web-api.md
- docs/walrus-sites/tutorial-publish.md
- mdbook-admonish.css
> feat: add admonitions

- docs/design/architecture.md
Rephrase the following sentence: "Each blob is erasure into encoded in many slivers."
> chore: fix typo

- docs/usage/setup.md
> docs: additional info on binary paths

- docs/walrus-sites/restrictions.md
> docs: add PWAs to restriction section

- .github/workflows/publish.yaml
- .github/workflows/update-binaries.yaml
> fix: store the docs and binaries for a little longer

- docs/usage/client-cli.md
- docs/usage/web-api.md
- po/messages.pot
- po/zh_CN.po
Closes WAL-337
⚠️ Should only be merged after the 1.5.0 release is complete.
> docs: document recent changes to the CLI and publisher

- docs/walrus-sites/builder-config.md
- docs/walrus-sites/commands.md
- docs/walrus-sites/portal.md
- docs/walrus-sites/tutorial-install.md
- docs/walrus-sites/tutorial-publish.md
> docs(walrus-sites): update stable branch mentions to refer to testnet

- docs/usage/client-cli.md
- docs/usage/web-api.md
- po/messages.pot
- po/zh_CN.po
⚠️ Should only be merged after the features are released
> docs(publisher): add information on new publisher behavior

- theme/head.hbs
> fix: fixed Cookbook Onboard bug with "s" key

- docs/usage/web-api.md
Added our aggregator and publisher endpoints
> docs: Brightlystake endpoints

- docs/usage/web-api.md
This PR adds some missing aggregators and publishers as well as updating some existing ones.
> chore: update aggregator/publisher list

- docs/usage/web-api.md
Added our aggregator and publisher
> docs: add stakepool aggregator and publisher

- docs/usage/web-api.md
to add nansen aggregator and publisher record
> docs: add nansen aggregator publisher record

- docs/usage/web-api.md
Updated the aggregator url to help reflect cache performance on Node Infra dashboard
> docs: update TPT aggregator url

- docs/usage/web-api.md
Update urls to reflect caching
> docs: update TPT Agg and Pub URLs

- docs/usage/web-api.md
Added TuDudes Walrus Aggregator and Publisher endpoints.
> docs: update web-api.md to include TuDudes

- docs/usage/web-api.md
Add "n1stake" aggregator and publisher to public list:
Aggregator: http://walrus-aggregator.n1stake.com:9000/
Publisher: http://walrus-publisher.n1stake.com:9001/
> docs: add "n1stake" aggregator and publisher to public list

- docs/usage/web-api.md
Adds public endpoints for Veera's aggregator and publisher nodes.
> docs: Add Veera aggregator and publisher endpoints

- docs/usage/web-api.md
> docs: update n1stake aggregator and publisher

- docs/usage/web-api.md
add http://walrus-testnet.equinoxdao.xyz:9001 http://walrus-testnet.equinoxdao.xyz:9000
> docs: add Equinox aggregator and publisher

- docs/usage/web-api.md
Adding senseinode publisher and aggregator endpoints
> chore: add senseinode endpoints

- docs/usage/sdks.md
- docs/usage/web-api.md
Reopening PR #265, after it was closed by accident.
@mlegner
> docs: add walrus php sdk in unofficial sdk list and add aggregator & publisher nodes 

- docs/usage/web-api.md
This PR adds the official KYVENetwork endpoints for Walrus.
> chore: add KYVENetwork Walrus endpoints for publisher and aggregator

- .github/workflows/publish.yaml
- docs/walrus-sites/overview.md
- examples/CONFIG/config_dir/README.md
- examples/python/hello_walrus_webapi.py
- Fix broken link.
- Don't block publishing on broken links.
- Fix instruction in `examples/python/hello_walrus_webapi.py`.
> chore: minor fixes

- README.md
> chore: add archival note
