- .github/workflows/publish.yaml
- Get SUI from correct faucet. 🤦 
- Only keep debug logs for site-builder and walrus.
- Remove colors.
> ci: improvements to the publish workflow

- .github/actions/set-up-walrus/action.yaml
- .github/workflows/publish.yaml
- .github/workflows/update-binaries.yaml
Successful workflow run: https://github.com/MystenLabs/walrus-docs/actions/runs/10006893810/job/27660483590
Closes #64
> ci: scheduled&manual workflow to update bin.walrus.site

- .github/workflows/update-binaries.yaml
Adding repository dispatch to the Update Binaries workflow.
> ci: add repository dispatch trigger for the update binaries workflow

- .github/actions/build-mdbook/action.yaml
- .github/workflows/publish.yaml
This avoids failures to publish the page when the linkcheck fails. The linkcheck is still performed for PRs but not when building the page for publishing on the `main` branch.
> ci: more robust linkcheck

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/docs.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
- .github/ISSUE_TEMPLATE/other.yaml
Adapted from the [walrus-sites](https://github.com/MystenLabs/walrus-sites) repository.
Closes #89
> chore: add issue templates

- docs/SUMMARY.md
- docs/dev-guide/dev-guide.md
- docs/operator-guide/aggregator.md
- docs/operator-guide/operator-guide.md
- docs/operator-guide/storage-node.md
Adding a `Operator Guide` to the walrus docs. Pretty light on details for now, but it can be built out as we get closer to testnet + working with operators.
Some TODOs:
* Deployment + upgrade guide
* disk and machine spec
* Cache and publisher operator guides
> docs: initial space for operator docs

- examples/python/hello_walrus_webapi.py
The prerequisites section in the code file requires to run Walrus in the daemon mode on the port 8899:
```python
#
```
but the script tries to access the walrus daemon by a different port:
```python
ADDRESS = "127.0.0.1:31415"
```
This PR fixes the port number in the code.
> fix(examples): Fixed the port number in the hello_walrus_webapi.py example

- book.toml
- docs/SUMMARY.md
- docs/blog/02_devnet_update.md
- docs/blog/03_whitepaper.md
Same content as on the [Mysten Labs blog](https://www.mystenlabs.com/blog/announcing-the-official-walrus-whitepaper) with slightly adjusted links.
Also makes capitalization in titles of the blog part of the docs consistent.
> docs: add whitepaper blog post

- examples/javascript/README.md
https://docs.walrus.site/usage/setup -> https://docs.walrus.site/usage/setup.html
right now says link is invalid
> fix: link for documentation is incorrect

- .github/workflows/lint.yaml
- docs/usage/stake.md
> feat: add overview of staking

- .github/workflows/publish.yaml
- .github/workflows/update-binaries.yaml
Updates the location of the site builder config to match the `walrus-sites` repo.
> chore: update the location of the site-builder config

- .github/actions/set-up-walrus/action.yaml
- .github/workflows/publish.yaml
- .github/workflows/update-binaries.yaml
See [this workflow run](https://github.com/MystenLabs/walrus-docs/actions/runs/11379789762/job/31657862945).
> ci: update Walrus setup to Testnet

- .github/actions/set-up-walrus/action.yaml
* use cache for rust to speed up building `sites-builder`
Contributes to #92
> chore: rust cache for walrus-sites

- docs/dev-guide/sui-struct.md
- docs/walrus-sites/portal.md
- docs/walrus-sites/routing.md
This PR fixes minor typos and improves clarity in documentation:
1. **`sui-struct.md`**: Fixed "need to rewritten" → "need to be rewritten".
Fixed "proof this" → "proof that this"
2. **`portal.md`**: Corrected "an browse" → "a browse".
3. **`routing.md`**: Resolved "only be only be" → "only be".
These changes enhance readability and maintain consistency across the docs.
> chore: fix some typos in the project documentation and code 

- .github/actions/set-up-walrus/action.yaml
- .github/workflows/publish.yaml
- .github/workflows/update-binaries.yaml
See https://github.com/MystenLabs/walrus-docs/actions/runs/12114599580/job/33771409749 for a workflow where the installation works. (The workflow fails for a different reason.)
Closes #92.
Closes WAL-413.
> ci: use pre-built site-builder binary

- theme/head.hbs
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Walrus resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Walrus, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.
Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Walrus-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.
> feat: Cookbook Onboard integration

- theme/head.hbs
Due to the bad interaction of the Cookbook integration and mdBook's keyboard shortcuts (see https://github.com/MystenLabs/walrus-docs/pull/184#issuecomment-2540798014), I'm removing the integration for now. This reverts commit 7fca07a0724a15a614d2fdc26c50ba2a4e42d062.
> fix: temporarily remove Cookbook Onboard integration

- docs/walrus-sites/linking.md
- docs/walrus-sites/portal.md
- The server portal is now hosted on `walrus.site` 
- The service-worker portal is no longer being hosted, but its' code is still available for local hosting.
> docs: update about portal hosting

- docs/usage/web-api.md
Adds Ruby Nodes to the list of publishers and aggregators.
> docs: add Ruby Nodes endpoints

- docs/usage/web-api.md
Adds Chainbase walrus endpoints to the list of publishers and aggregators.
> docs: add Chainbase walrus endpoints

- docs/walrus-sites/authentication.md
- docs/walrus-sites/intro.md
- docs/walrus-sites/overview.md
- docs/walrus-sites/restrictions.md
- docs/walrus-sites/tutorial-publish.md
- Update `intro.md`: there was a mention to the service worker that we missed in the past. 
- Update the `restrictions.md`. 
- Fix typos.
> chore: update the walrus sites docs to align with 

- docs/usage/web-api.md
Adds StakeCraft to the list of publishers and aggregators.
> docs: add StakeCraft endpoints

- docs/usage/web-api.md
Added https to publisher and unique link for aggregator
> docs: update Staking Defense League Agg and Pub URLs

- docs/walrus-sites/portal.md
Related to https://github.com/MystenLabs/walrus-sites/pull/369.
> docs(portal): update the portal deployment docs

- docs/usage/web-api.md
Removed Stardust Staking publisher/aggregator proxy ports and replaced them with a simple SSL setup for **improved security and easier usage.**
> docs: update Stardust Staking endpoints

- docs/usage/web-api.md
Updated the endpoint to use the domain of the officially registered entity.
> docs: update BartestneT Web API endpoints
